### ISSUE TITLE
QScintilla2 on Linux?

### ISSUE THREAD

**Issue by jurov** [Shinmera/qt-libs#8]
On Gentoo Linux x64 I do have /usr/lib64/qt4/libqscintilla2.so installed and qt-libs compiles from quicklisp and works fine, but  (qt:ensure-smoke :qscintilla2) fails with "Unable to load foreign library (LIBSMOKEQSCINTILLA2.SO-988)" - smoke bindings are not generated.

If I read qt4.lisp correctly, qscintilla2 gets built only on Windows, why?

**Comment by Shinmera** [comment]
I'm not sure where you read that it's only built on Windows.

It is included on all platforms, but the Smoke binding isn't called "qscintilla2", but rather "qsci". Don't ask me why, that name decision is part of Smoke.

**Comment by jurov** [comment]
I have read the find-local-files method.

Huh qsci? That would be very good to document, will do pull request for about.html.

**Comment by Shinmera** [comment]
Yeah, and I don't see where that method says anything about qscintilla being Windows-only.

The html is auto-generated. Don't modify it.

**Comment by jurov** [comment]
Never mind, I badly misread it. What about editing README.md?

**Comment by Shinmera** [comment]
As I said, I wouldn't know where to put it. It's not really something that qt-libs decides on or deals with, but rather a Smoke intricacy.

**Comment by jurov** [comment]
I think, it's all in vain,  :qsci loads but (qdescribe "QsciScintilla") throws error both in ecl and sbcl - should it be reported here or in commonqt? Thanks for patience.

**Comment by Shinmera** [comment]
This project is about compiling and providing the libraries cross-platform. Everything that actually uses the bindings is a CommonQt problem.

However, the error might be due to a problem in CommonQt, due to a problem in Smoke, or due to a problem in the specific compiled versions that Qt-libs provides, so it would be appropriate for any one of those depending on what the actual cause is. For now I'd open up a ticket with CommonQt and leave this one open until the situation is more clear.
